'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
const {expect} = require('@playwright/test');

// All actions below operate on the real renderer/preload of the released app.
// No API responses, device facts or production modules are injected.
async function verifyPackagedUI({application, page, profile, artifactDirectory, evidence, checkpoint, rom2, restart}) {
  const shot = name => page.screenshot({path:path.join(artifactDirectory, name)});
  const state = () => page.evaluate(() => window.renewAPI.getState());
  const button = name => page.getByRole('button',{name,exact:true});
  const settings = async tab => { await button('Settings').click(); await page.getByRole('tab',{name:tab,exact:true}).click(); };
  const paletteSearch = () => page.getByRole('searchbox',{name:'Find a command or game',exact:true});
  checkpoint('ui:home-selection');
  await expect(page.locator('[data-shelf="unplayed"] .game-card')).toHaveCount(2);
  await expect(page.locator('#hero-title')).toHaveText('Renew smoke animation');
  const shelf = page.locator('[data-shelf="unplayed"]');
  await shelf.getByRole('button',{name:'Select Renew smoke animation',exact:true}).focus();
  await page.keyboard.press('ArrowRight');
  await expect(shelf.getByRole('button',{name:'Select Second authored sample',exact:true})).toBeFocused();
  await page.keyboard.press('Enter');
  assert.equal((await state()).session, null, 'Home keyboard selection does not launch.');
  await expect(page.locator('#hero-title')).toHaveText('Second authored sample');
  await expect(page.locator('#app')).toHaveAttribute('data-palette','ocean');
  await shot('packaged-home.png');
  evidence.checks.homeSelection = true;

  checkpoint('ui:search-filters-selection');
  await page.getByRole('searchbox',{name:'Find a game'}).fill('smoke');
  await expect(page.getByRole('heading',{name:'Library',exact:true})).toBeVisible();
  await expect(page.locator('.game-card')).toHaveCount(1);
  await expect(page.locator('#hero-title')).toHaveText('Renew smoke animation');
  await page.getByRole('searchbox',{name:'Find a game'}).fill('no such game');
  await expect(page.getByRole('heading',{name:'No games in this view.'})).toBeVisible();
  await expect(button('Play game')).toHaveCount(0);
  await page.keyboard.press('Enter');
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await button('Clear filters').click();
  await expect(page.locator('.game-card')).toHaveCount(2);
  await button('Game Boy Color').click();
  await expect(page.locator('.game-card')).toHaveCount(0);
  await button('Game Boy').click();
  await expect(page.locator('.game-card')).toHaveCount(0);
  await button('Game Boy Advance').click();
  await expect(page.locator('.game-card')).toHaveCount(2);
  await button('Select Second authored sample').focus();
  await page.keyboard.press('Enter');
  await expect(page.locator('#hero-title')).toHaveText('Second authored sample');
  assert.equal((await state()).session, null, 'Keyboard selection does not launch.');
  evidence.checks.searchFiltersKeyboardSelection = true;

  checkpoint('ui:details-favorites-views');
  await button('Select Renew smoke animation').click();
  await button('Details for Renew smoke animation').click();
  await page.getByRole('textbox',{name:'Display name'}).fill('');
  await button('Save name').click();
  await expect(page.getByRole('dialog')).toBeVisible();
  assert.equal(await page.getByRole('textbox',{name:'Display name'}).evaluate(input=>input.validity.valid), false);
  await page.getByRole('textbox',{name:'Display name'}).fill('Verified authored animation');
  await button('Save name').click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await expect(page.locator('#hero-title')).toHaveText('Verified authored animation');
  await button('Add to favorites').click();
  await button('Favorites').click();
  await expect(page.locator('.game-card')).toHaveCount(1);
  await expect(page.locator('.card-title')).toHaveText('Verified authored animation');
  await button('Library').click();
  await page.getByRole('combobox',{name:'Sort games'}).selectOption('recent');
  await expect(page.locator('.card-title')).toHaveText(['Verified authored animation','Second authored sample']);
  await page.getByRole('combobox',{name:'Sort games'}).selectOption('title');
  await expect(page.locator('.card-title')).toHaveText(['Second authored sample','Verified authored animation']);
  await button('List view').click();
  await expect(page.locator('.game-grid')).toHaveClass(/list-layout/);
  await button('Grid view').click();
  await expect(page.locator('.game-grid')).not.toHaveClass(/list-layout/);
  await button('Expand navigation menu').click();
  await expect(button('Collapse navigation menu')).toHaveAttribute('aria-expanded','true');
  await page.reload();
  await expect(button('Collapse navigation menu')).toBeVisible();
  await button('Collapse navigation menu').click();
  await button('Library').click();
  await expect(page.locator('.game-card')).toHaveCount(2);
  await shot('packaged-library.png');
  evidence.checks.renameFavoritesSortViewsSidebar = true;

  checkpoint('ui:settings');
  await settings('Emulator');
  await expect(page.getByRole('tabpanel',{name:'Emulator',exact:true})).toContainText('mGBA.exe');
  await page.getByRole('tab',{name:'Emulator',exact:true}).focus();
  await page.keyboard.press('ArrowDown');
  await expect(page.getByRole('tab',{name:'Launch',exact:true})).toBeFocused();
  await page.getByRole('switch',{name:'Start games fullscreen'}).uncheck();
  await page.getByRole('switch',{name:'Come back to Renew',exact:true}).uncheck();
  await button('Close settings').click();
  await expect(button('Settings')).toBeFocused();
  assert.equal((await state()).settings.fullscreen, false);
  assert.equal((await state()).settings.returnToLauncher, false);
  await settings('Launch');
  await expect(page.getByRole('switch',{name:'Start games fullscreen'})).not.toBeChecked();
  await expect(page.getByRole('switch',{name:'Come back to Renew',exact:true})).not.toBeChecked();
  await page.getByRole('dialog').press('Escape');
  await expect(button('Settings')).toBeFocused();
  evidence.checks.settingsActualIPCAndDismissal = true;

  checkpoint('ui:power-device');
  await expect(button('Open command palette')).toHaveCount(0);
  await settings('Power user');
  await expect(page.getByRole('switch',{name:'Power user tools',exact:true})).not.toBeChecked();
  await expect(page.getByRole('switch',{name:'Command palette',exact:true})).toBeDisabled();
  await page.getByRole('switch',{name:'Power user tools',exact:true}).check();
  await page.getByRole('switch',{name:'Command palette',exact:true}).check();
  await button('Read device information').click();
  const device = await page.evaluate(()=>window.renewAPI.getDeviceInfo());
  const expected = {runtimePlatform:'win32',runtimeArchitecture:'x64',reportedSystemVersion:os.release(),renewVersion:'0.1.0',electronVersion:'44.5.1'};
  assert.equal(device.version,1);
  for (const [key,value] of Object.entries(expected)) { assert.equal(device[key].status,'reported'); assert.equal(device[key].value,value); }
  evidence.deviceInfo = device;
  await expect(page.locator('#device-info')).toContainText('44.5.1');
  await expect(page.locator('#device-info')).toContainText('Not identified');
  await expect(page.locator('#device-info')).toContainText('Wine');
  await page.locator('#device-info').scrollIntoViewIfNeeded();
  await shot('packaged-device-info.png');
  await button('Done').click();
  await page.reload();
  await expect(button('Open command palette')).toBeVisible();
  evidence.checks.powerEnableReloadDeviceInfo = true;
  await button('Expand navigation menu').click();
  checkpoint('ui:enabled-preferences-portable-restart');
  ({application, page} = await restart());
  await expect(button('Open command palette')).toBeVisible();
  await expect(button('Collapse navigation menu')).toBeVisible();
  await button('Collapse navigation menu').click();
  evidence.checks.enabledPowerAndSidebarPortableRestart = true;

  checkpoint('ui:palette');
  await button('Open command palette').focus();
  await page.keyboard.press('Control+k');
  await expect(paletteSearch()).toBeFocused();
  await paletteSearch().fill('Open Library');
  await page.keyboard.press('ArrowDown');
  await expect(page.locator('[data-power-command="library"]')).toBeFocused();
  await page.keyboard.press('Enter');
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await expect(page.locator('#collection-title')).toBeFocused();
  await button('Open command palette').click();
  await paletteSearch().fill('Pick an unplayed');
  await page.keyboard.press('Enter');
  await expect(page.locator('.game-art-button:focus')).toHaveAttribute('aria-pressed','true');
  assert.equal((await state()).session,null,'Pick unplayed only selects.');
  await button('Open command palette').click();
  await paletteSearch().fill('no such command');
  await expect(page.locator('#palette-results')).toHaveText('No matching commands.');
  await shot('packaged-palette.png');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await expect(button('Open command palette')).toBeFocused();
  evidence.checks.paletteNavigationPickAndEscape = true;

  checkpoint('ui:power-reset');
  const beforeReset = await state();
  await settings('Power user');
  await page.getByRole('switch',{name:'Power user tools',exact:true}).uncheck();
  await expect(page.getByRole('switch',{name:'Command palette',exact:true})).toBeChecked();
  await expect(page.getByRole('switch',{name:'Command palette',exact:true})).toBeDisabled();
  await page.getByRole('switch',{name:'Power user tools',exact:true}).check();
  await button('Reset Power user tools').click();
  await expect(page.getByRole('switch',{name:'Power user tools',exact:true})).not.toBeChecked();
  await expect(page.getByRole('switch',{name:'Command palette',exact:true})).not.toBeChecked();
  await button('Done').click();
  await expect(button('Open command palette')).toHaveCount(0);
  assert.deepEqual(await state(),beforeReset,'Power reset preserves library and launch settings.');
  await settings('Launch');
  await page.getByRole('switch',{name:'Start games fullscreen'}).check();
  await page.getByRole('switch',{name:'Come back to Renew',exact:true}).check();
  await button('Done').click();
  evidence.checks.powerMasterDisableAndResetIsolation = true;

  checkpoint('ui:remove');
  await button('Details for Second authored sample').click();
  await button('Remove').click();
  await button('Keep game').click();
  await expect(page.locator('.game-card')).toHaveCount(2);
  await button('Details for Second authored sample').click();
  await button('Remove').click();
  await button('Remove from library').click();
  await expect(page.locator('.game-card')).toHaveCount(1);
  assert.ok((await fs.stat(rom2)).isFile(),'Removing the entry leaves the authored ROM untouched.');
  const persisted=JSON.parse(await fs.readFile(path.join(profile,'library.json'),'utf8'));
  assert.equal(persisted.games.length,1);
  assert.equal(persisted.games[0].favorite,true);
  assert.equal(persisted.games[0].title,'Verified authored animation');
  evidence.checks.removalCancelConfirmPreservesFile = true;
}
module.exports={verifyPackagedUI};
