import {escapeHTML as esc, formatRecordedTime, platformName} from './model.js';
import {icon, artwork} from './visuals.js';
import {selectHomeCollections} from './home.js';
import {visibleGames, sessionGame, viewTitle} from './navigation.js';

export function renderShell({state, ui, selectedId, busy, isPreview}) {
  const games = visibleGames(state, ui);
  const selected = games.find(game => game.id === selectedId) || games[0];
  const counts = system => state.games.filter(game => !system || game.system === system).length;
  return `<aside class="sidebar" id="sidebar-navigation">
    <a class="brand" data-focus="brand" href="#home" aria-label="Renew home"><span class="brand-mark"><svg viewBox="0 0 32 32" aria-hidden="true"><path fill="currentColor" d="M25 3a13 13 0 1 0 4 18A11 11 0 1 1 25 3Z"/></svg></span><span class="brand-word">RENEW</span></a>
    <nav aria-label="Main navigation">
      <button class="nav-item ${ui.view === 'home' ? 'active' : ''}" data-action="nav" data-view="home" data-focus="nav-home" aria-label="Home" title="Home" ${ui.view === 'home' ? 'aria-current="page"' : ''}>${icon('home')}<span>Home</span></button>
      <button class="nav-item ${['library', 'recent', 'unplayed'].includes(ui.view) ? 'active' : ''}" data-action="nav" data-view="library" data-focus="nav-library" aria-label="Library" title="Library">${icon('grid')}<span>Library</span><span class="nav-count">${counts()}</span></button>
      <button class="nav-item ${ui.view === 'favorites' ? 'active' : ''}" data-action="nav" data-view="favorites" data-focus="nav-favorites" aria-label="Favorites" title="Favorites">${icon('heart')}<span>Favorites</span><span class="nav-count">${state.games.filter(g => g.favorite).length}</span></button>
      <button class="nav-item" data-action="import" data-focus="quick-import" aria-label="Add games from quick actions" title="Add games" ${busy ? 'disabled' : ''}>${icon('plus')}<span>Add games</span></button>
    </nav>
    <div class="sidebar-section">SYSTEMS</div>
    <nav class="system-navigation" aria-label="Filter by system">
      ${[['GBA','Game Boy Advance','gba'],['GBC','Game Boy Color','gbc'],['GB','Game Boy','gb']].map(([key,label,cls]) => `<button class="system-item ${ui.system === key ? 'selected' : ''}" data-action="system" data-system="${key}" data-focus="system-${key}" aria-label="${label}" title="${label}" aria-pressed="${ui.system === key}"><span class="system-device ${cls}"><i></i></span><span>${label}</span><span class="system-count">${counts(key)}</span></button>`).join('')}
    </nav>
    <button class="menu-toggle" data-action="toggle-menu" data-focus="menu-toggle" aria-controls="sidebar-navigation" aria-expanded="${!ui.sidebarCollapsed}" aria-label="${ui.sidebarCollapsed ? 'Expand navigation menu' : 'Collapse navigation menu'}" title="${ui.sidebarCollapsed ? 'Expand menu' : 'Collapse menu'}">${icon('chevron')}<span>Collapse menu</span></button>
    <div class="sidebar-bottom"><button class="nav-item" data-action="settings" data-focus="settings" aria-label="Settings" title="Settings">${icon('settings')}<span>Settings</span></button><div class="build-label">FIRST LIGHT <span>v0.1.0</span></div></div>
  </aside>
  <div class="workspace">
    <div class="scene" aria-hidden="true"><img src="${selected ? artwork(selected) : './art/orchard-v1.png'}" alt=""><div class="scene-shade"></div></div>
    <header class="topbar"><div class="breadcrumb"><span class="topbar-brand">RENEW</span><span class="breadcrumb-divider"></span><h1>${viewTitle(ui.view)}</h1></div>
      <div class="topbar-right"><button class="topbar-settings" data-action="settings" data-focus="quick-settings" aria-label="Open launcher settings">${icon('settings')}<span>Settings</span></button>${isPreview ? '<span class="preview-pill">INTERACTIVE PREVIEW</span>' : '<span class="desktop-pill">WINDOWS · mGBA</span>'}${!isPreview ? `<div class="window-controls"><button data-action="window" data-command="minimize" aria-label="Minimize">${icon('minimize')}</button><button data-action="window" data-command="maximize" aria-label="Maximize or restore">${icon('maximize')}</button><button data-action="window" data-command="close" aria-label="Close Renew">${icon('close')}</button></div>` : ''}</div>
    </header>
    <main id="main">
      ${state.warning ? `<div class="notice warning" role="alert">${icon('warning')}<span>${esc(state.warning)}</span></div>` : ''}
      ${state.error ? `<div class="notice warning" role="alert">${icon('warning')}<span>${esc(state.error.message || state.error)}</span></div>` : ''}
      ${selected ? hero(selected) : emptyHero()}
      ${ui.view === 'home' ? homeCollections() : libraryCollection()}
      <footer class="page-footer"><span>${icon('folder')} Local library <span class="footer-separator">·</span><button data-action="settings" data-focus="overview-settings" aria-label="Configure launch preferences">${state.settings.emulatorPath ? 'mGBA ready' : 'Set up mGBA'}</button></span><div>${isPreview ? '<span class="preview-note">Sample titles · Native gameplay is not running</span>' : ''}<kbd>Tab</kbd> Browse <kbd>Enter</kbd> Activate <kbd>/</kbd> Search</div></footer>
    </main>
  </div>`;


  function libraryCollection() { return `<section class="collection" aria-labelledby="collection-title"><div class="collection-header"><div class="section-title"><h2 id="collection-title" tabindex="-1" data-focus="content-heading">${ui.view === 'favorites' ? 'Your favorites' : ui.view === 'library' ? 'Your library' : viewTitle(ui.view)}</h2><span>${games.length} ${games.length === 1 ? 'game' : 'games'}</span></div><button class="button add-button" data-action="import" data-focus="import" ${busy ? 'disabled' : ''}>${icon('plus')} Add games</button></div>
        <div class="collection-toolbar"><div class="filter-bar"><button data-action="system" data-system="all" data-focus="filter-all" class="filter-chip ${ui.system === 'all' ? 'active' : ''}" aria-pressed="${ui.system === 'all'}">All games <span>${counts()}</span></button>${['GBA','GBC','GB'].map(s => `<button data-action="system" data-system="${s}" data-focus="filter-${s}" class="filter-chip ${ui.system === s ? 'active' : ''}" aria-pressed="${ui.system === s}">${s} <span>${counts(s)}</span></button>`).join('')}</div>
        <div class="collection-tools"><label class="search-box">${icon('search')}<input id="search" data-focus="search" type="search" placeholder="Find a game" aria-label="Find a game" value="${esc(ui.query)}"><kbd>/</kbd></label><label class="sort-label"><span class="sr-only">Sort games</span><select id="sort" data-focus="sort"><option value="recent" ${ui.sort === 'recent' ? 'selected' : ''}>Recently played</option><option value="title" ${ui.sort === 'title' ? 'selected' : ''}>Title A–Z</option><option value="played" ${ui.sort === 'played' ? 'selected' : ''}>Most played</option></select></label><div class="layout-switch" aria-label="View style"><button data-action="layout" data-layout="grid" data-focus="layout-grid" aria-label="Grid view" aria-pressed="${ui.layout === 'grid'}">${icon('grid')}</button><button data-action="layout" data-layout="list" data-focus="layout-list" aria-label="List view" aria-pressed="${ui.layout === 'list'}">${icon('list')}</button></div></div></div>
        ${games.length ? `<div data-shelf="library" class="game-grid ${ui.layout === 'list' ? 'list-layout' : ''}" aria-label="Game shelf">${games.map(game => card(game)).join('')}</div>` : emptyCollection()}
      </section>`; }
  function homeCollections() {
    const groups = selectHomeCollections(state.games, {...ui, session: state.session});
    const current = sessionGame(state, ui);
    const descriptions = {recent: 'Your latest recorded sessions on this computer.', favorites: 'The games you have kept close.', unplayed: 'No recorded play history in Renew on this computer.'};
    const empty = {recent: 'Play a game with Renew and it will appear here.', favorites: 'Use the heart on a game to keep it close.', unplayed: state.games.length ? 'No unplayed games in this view.' : 'Add your games to start exploring.'};
    return `<section class="collection home-collection" aria-labelledby="collection-title">
      <div class="collection-header"><div class="section-title"><h2 id="collection-title" tabindex="-1" data-focus="content-heading">A little time for you</h2><span>${state.games.length} ${state.games.length === 1 ? 'game' : 'games'} in your library</span></div><div class="home-actions"><button class="button subtle" data-action="nav" data-view="library" data-focus="home-library">Open Library ${icon('chevron')}</button><button class="button add-button" data-action="import" data-focus="import" ${busy ? 'disabled' : ''}>${icon('plus')} Add games</button></div></div>
      <div class="collection-toolbar"><div class="filter-bar"><button data-action="system" data-system="all" data-focus="filter-all" class="filter-chip ${ui.system === 'all' ? 'active' : ''}" aria-pressed="${ui.system === 'all'}">All games <span>${counts()}</span></button>${['GBA','GBC','GB'].map(s => `<button data-action="system" data-system="${s}" data-focus="filter-${s}" class="filter-chip ${ui.system === s ? 'active' : ''}" aria-pressed="${ui.system === s}">${s} <span>${counts(s)}</span></button>`).join('')}</div><div class="collection-tools"><label class="search-box">${icon('search')}<input id="search" data-focus="search" type="search" placeholder="Search your library" aria-label="Find a game" value="${esc(ui.query)}"><kbd>/</kbd></label></div></div>
      ${current ? `<div class="home-session" role="status">${icon('game')}<span>${state.session.status === 'launching' ? 'Starting in mGBA' : 'Open in mGBA'} <strong>${esc(current.title)}</strong></span><button class="text-button" data-action="select" data-id="${esc(current.id)}" data-focus="session-select">Select this game</button></div>` : ''}
      ${groups.map(group => `<section class="home-group" aria-labelledby="home-${group.id}-title"><div class="home-group-heading"><div><h3 id="home-${group.id}-title">${group.title} <span>${group.total}</span></h3><p>${descriptions[group.id]}</p></div>${group.total ? `<button class="text-button" data-action="collection" data-view="${group.id}" data-focus="home-all-${group.id}">See all<span class="sr-only"> ${group.title}</span> ${icon('chevron')}</button>` : ''}</div>${group.games.length ? `<div class="game-grid home-shelf" data-shelf="${group.id}" aria-label="${group.title}">${group.games.map(game => card(game, group.id)).join('')}</div>` : `<div class="home-group-empty"><p>${empty[group.id]}</p></div>`}</section>`).join('')}
      ${ui.system !== 'all' ? '<button class="text-button" data-action="reset-filters" data-focus="home-clear-filters">Clear filters</button>' : ''}
    </section>`;
  }

  function hero(game) {
    const session = state.session?.gameId === game.id;
    return `<section class="hero" aria-labelledby="hero-title"><div class="hero-copy"><span class="hero-kicker">${session ? state.session.status === 'launching' ? 'YOUR GAME IS STARTING' : 'OPEN IN mGBA' : 'SELECTED GAME'}</span><h2 id="hero-title" title="${esc(game.title)}">${esc(game.title)}</h2><div class="hero-rule"></div><div class="hero-system">${esc(platformName(game.system))}<span>·</span>mGBA${game.sample ? '<span class="sample-label">SAMPLE</span>' : ''}</div><div class="hero-actions"><button class="button play-button" data-action="play" data-id="${esc(game.id)}" data-focus="hero-play" aria-label="${session ? state.session.status === 'launching' ? 'Starting game' : 'Playing' : 'Play game'}" ${busy || state.session ? 'disabled' : ''}>${icon('play')} ${session ? state.session.status === 'launching' ? 'Starting…' : 'Playing' : 'Play'}</button><button class="button details-button" data-action="details" data-id="${esc(game.id)}" data-focus="overview-details-${esc(game.id)}" aria-label="Edit selected game details">Details</button><button class="hero-favorite ${game.favorite ? 'is-favorite' : ''}" data-action="favorite" data-id="${esc(game.id)}" data-focus="hero-favorite" ${busy ? 'disabled' : ''} aria-label="${game.favorite ? 'Remove from' : 'Add to'} favorites" aria-pressed="${game.favorite}" title="${game.favorite ? 'Remove from' : 'Add to'} favorites">${icon('heart')}</button></div><div class="hero-meta">${icon('clock')} ${esc(formatRecordedTime(game, state.session))}<span>·</span>${session ? 'Renew will be here when you return' : 'Original Renew artwork · Colors follow this scene'}</div></div></section>`;
  }
  function emptyHero() {
    if (state.games.length) return `<section class="hero empty-hero"><div class="hero-copy"><span class="hero-kicker">YOUR LIBRARY</span><h2>No games in this view.</h2><div class="hero-rule"></div><p>Change your search, filters or library view to select a game.</p></div></section>`;
    return `<section class="hero empty-hero"><div class="hero-copy"><span class="hero-kicker">A FRESH START</span><h2>A new home for<br>old favorites.</h2><div class="hero-rule"></div><p>Add your games. Choose mGBA. Make time to play.</p><button class="button play-button" data-action="import" data-focus="empty-import" ${busy ? 'disabled' : ''}>${icon('plus')} Add your first game</button><div class="hero-meta">GBA, Game Boy Color & Game Boy</div></div></section>`; }
  function card(game, shelf = '') { const focus = name => `${shelf ? `${shelf}-` : ''}${name}-${esc(game.id)}`; return `<article class="game-card ${selectedId === game.id ? 'selected-card' : ''}"><button class="game-art-button" data-action="select" data-id="${esc(game.id)}" data-focus="${focus('select')}" aria-label="Select ${esc(game.title)}" aria-pressed="${selectedId === game.id}"><img src="${artwork(game)}" alt="" loading="lazy"><span class="cover-wordmark" aria-hidden="true">${esc(game.title)}</span><span class="cover-system">${esc(game.system)}</span><span class="cover-select">${icon('check')}</span></button><div class="card-info"><div><button class="card-title" title="${esc(game.title)}" data-action="select" data-id="${esc(game.id)}" data-focus="${focus('title')}">${esc(game.title)}</button><p>${esc(shelf === 'unplayed' ? 'No recorded play in Renew' : formatRecordedTime(game, state.session))}${game.sample ? ' · Sample' : ''}</p></div><button class="card-menu" data-action="details" data-id="${esc(game.id)}" data-focus="${focus('details')}" aria-label="Details for ${esc(game.title)}">${icon('more')}</button></div>${game.favorite ? `<span class="card-favorite" aria-label="Favorite">${icon('heart')}</span>` : ''}</article>`; }
  function emptyCollection() { return `<div class="empty-collection">${icon(ui.query ? 'search' : ui.view === 'favorites' ? 'heart' : 'game')}<h3>${ui.query ? 'No games found' : ui.view === 'favorites' ? 'Make room for your favorites' : ui.view === 'recent' ? 'Your next session starts here' : ui.view === 'unplayed' ? 'No unplayed games in this view' : ui.system !== 'all' ? 'No games for this system yet' : 'A good collection starts with one.'}</h3><p>${ui.query ? 'Try a different name or clear your filters.' : ui.view === 'favorites' ? 'Use the heart on a game to keep it close.' : ui.view === 'recent' ? 'Your recorded Renew sessions will appear here.' : ui.view === 'unplayed' ? 'This view only uses play history recorded by Renew on this computer.' : 'Add uncompressed .gba, .gbc or .gb files from your computer.'}</p>${ui.query || ui.system !== 'all' ? '<button class="button subtle" data-action="reset-filters" data-focus="reset-filters">Clear filters</button>' : ui.view !== 'favorites' ? `<button class="button subtle" data-action="import" data-focus="empty-collection-import" ${busy ? 'disabled' : ''}>Add games</button>` : ''}</div>`; }
}
