import {escapeHTML as esc, formatTime, selectGames, platformName, artForId} from './model.js';
import {icon, artwork} from './visuals.js';

export function renderShell({state, ui, selectedId, busy, isPreview}) {
function counts(system) { return state.games.filter(game => !system || game.system === system).length; }
  const games = selectGames(state.games, ui);
  const selected = state.games.find(game => game.id === selectedId) || games[0];
  return `<aside class="sidebar" id="sidebar-navigation">
    <button class="menu-toggle" data-action="toggle-menu" data-focus="menu-toggle" aria-controls="sidebar-navigation" aria-expanded="${!ui.sidebarCollapsed}" aria-label="${ui.sidebarCollapsed ? 'Expand navigation menu' : 'Collapse navigation menu'}" title="${ui.sidebarCollapsed ? 'Expand menu' : 'Collapse menu'}">${icon('list')}</button>
    <a class="brand" href="#library" aria-label="Renew library"><span class="brand-mark"><svg viewBox="0 0 32 25" aria-hidden="true"><path fill="currentColor" d="M1 22C5-6 27-6 31 22 23 8 9 8 1 22Z"/></svg></span><span class="brand-word">RENEW<small>YOUR SPACE TO PLAY</small></span></a>
    <div class="sidebar-section">YOUR SPACE</div>
    <nav aria-label="Main navigation">
      <button class="nav-item ${ui.view === 'library' ? 'active' : ''}" data-action="nav" data-view="library" data-focus="nav-library" aria-label="Library" title="Library">${icon('grid')}<span>Library</span><span class="nav-count">${counts()}</span></button>
      <button class="nav-item ${ui.view === 'favorites' ? 'active' : ''}" data-action="nav" data-view="favorites" data-focus="nav-favorites" aria-label="Favorites" title="Favorites">${icon('heart')}<span>Favorites</span><span class="nav-count">${state.games.filter(g => g.favorite).length}</span></button>
    </nav>
    <div class="sidebar-section systems-label">YOUR SYSTEMS</div>
    <nav aria-label="Filter by system">
      ${[['GBA','Game Boy Advance','gba'],['GBC','Game Boy Color','gbc'],['GB','Game Boy','gb']].map(([key,label,cls]) => `<button class="system-item ${ui.system === key ? 'selected' : ''}" data-action="system" data-system="${key}" data-focus="system-${key}" aria-label="${label}" title="${label}" aria-pressed="${ui.system === key}"><span class="system-device ${cls}"><i></i></span><span>${label}</span><span class="system-count">${counts(key)}</span></button>`).join('')}
    </nav>
    <div class="sidebar-bottom">
      <div class="local-note"><span class="status-dot"></span><div>On this computer<small>Your library. Your progress.</small></div></div>
      <button class="nav-item" data-action="settings" data-focus="settings" aria-label="Settings" title="Settings">${icon('settings')}<span>Settings</span></button>
      <div class="build-label">FIRST LIGHT <span>v0.1.0</span></div>
    </div>
  </aside>
  <div class="workspace">
    <header class="topbar"><div class="breadcrumb">Your space ${icon('chevron')} <span>${ui.view === 'favorites' ? 'Favorites' : 'Library'}</span></div>
      <div class="topbar-right">${isPreview ? '<span class="preview-pill">INTERACTIVE PREVIEW</span>' : '<span class="desktop-pill">WINDOWS · mGBA</span>'}
      ${!isPreview ? `<div class="window-controls"><button data-action="window" data-command="minimize" aria-label="Minimize">${icon('minimize')}</button><button data-action="window" data-command="maximize" aria-label="Maximize or restore">${icon('maximize')}</button><button data-action="window" data-command="close" aria-label="Close Renew">${icon('close')}</button></div>` : '<span class="profile-mark" aria-label="Local library">r.</span>'}</div>
    </header>
    <main id="main">
      <section class="page-heading"><div><div class="eyebrow">YOUR LIBRARY. ALL TOGETHER.</div><h1>${ui.view === 'favorites' ? 'The ones you love.' : 'Your next little escape.'}</h1><p>A familiar world, one play away.</p></div><button class="button primary add-button" data-action="import" data-focus="import" ${busy ? 'disabled' : ''}>${icon('plus')} Add games</button></section>
      ${state.warning ? `<div class="notice warning" role="alert">${icon('warning')}<span>${esc(state.warning)}</span></div>` : ''}
      ${state.error ? `<div class="notice warning" role="alert">${icon('warning')}<span>${esc(state.error.message || state.error)}</span></div>` : ''}
      ${isPreview ? '<div class="preview-note">Visual preview · Original sample titles and artwork · Native gameplay is not running</div>' : ''}
      <div class="dashboard-top">${selected ? hero(selected) : emptyHero()}${quickPanel(selected)}</div>
      <section class="collection" aria-labelledby="collection-title"><div class="collection-header"><div class="section-title"><h2 id="collection-title">${ui.view === 'favorites' ? 'Your favorites' : 'Your collection'}</h2><span>${games.length} ${games.length === 1 ? 'game' : 'games'}</span></div><div class="collection-tools"><label class="search-box">${icon('search')}<input id="search" data-focus="search" type="search" placeholder="Find a game" aria-label="Find a game" value="${esc(ui.query)}"><kbd>/</kbd></label><label class="sort-label"><span class="sr-only">Sort games</span><select id="sort" data-focus="sort"><option value="recent" ${ui.sort === 'recent' ? 'selected' : ''}>Recently played</option><option value="title" ${ui.sort === 'title' ? 'selected' : ''}>Title A–Z</option><option value="played" ${ui.sort === 'played' ? 'selected' : ''}>Most played</option></select></label><div class="layout-switch" aria-label="View style"><button data-action="layout" data-layout="grid" data-focus="layout-grid" aria-label="Grid view" aria-pressed="${ui.layout === 'grid'}">${icon('grid')}</button><button data-action="layout" data-layout="list" data-focus="layout-list" aria-label="List view" aria-pressed="${ui.layout === 'list'}">${icon('list')}</button></div></div></div>
        <div class="filter-bar"><button data-action="system" data-system="all" data-focus="filter-all" class="filter-chip ${ui.system === 'all' ? 'active' : ''}" aria-pressed="${ui.system === 'all'}">All games <span>${counts()}</span></button>${['GBA','GBC','GB'].map(s => `<button data-action="system" data-system="${s}" data-focus="filter-${s}" class="filter-chip ${ui.system === s ? 'active' : ''}" aria-pressed="${ui.system === s}">${s} <span>${counts(s)}</span></button>`).join('')}<span class="library-caption">YOUR LIBRARY, YOUR PACE</span></div>
        ${games.length ? `<div class="game-grid ${ui.layout === 'list' ? 'list-layout' : ''}">${games.map(game => card(game)).join('')}</div>` : emptyCollection()}
      </section>
      ${dashboardPanels(selected)}
      <footer class="page-footer"><span>${icon('game')} Your games. A space of your own.</span><div><kbd>/</kbd> Search <kbd>Esc</kbd> Close ${icon('keyboard')}</div></footer>
    </main>
  </div>`;

function quickPanel() {
  return `<aside class="dashboard-panel quick-panel" aria-label="Quick actions"><h3>${icon('game')} Quick actions</h3><button class="quick-action" data-action="import" data-focus="quick-import" aria-label="Add games from quick actions" ${busy ? 'disabled' : ''}>${icon('plus')}<span>Add games</span></button><button class="quick-action" data-action="settings" data-focus="quick-settings" aria-label="Open launcher settings">${icon('settings')}<span>Settings</span></button><div class="quick-footer"><i class="status-dot"></i>${isPreview ? 'Interactive preview' : 'On this computer'}</div></aside>`;
}
function dashboardPanels(game) {
  return `<section class="dashboard-bottom" aria-label="Launcher overview"><article class="dashboard-panel game-overview"><h3>${icon('clock')} Selected game</h3>${game ? `<div class="selected-summary"><img src="${artwork(game)}" alt=""><div><strong>${esc(game.title)}</strong><span>${esc(platformName(game.system))}</span><small>${esc(formatTime(game.playSeconds))}</small></div><button class="button subtle" data-action="details" data-id="${esc(game.id)}" data-focus="overview-details-${esc(game.id)}" aria-label="Edit selected game details">Details ${icon('chevron')}</button></div>` : `<p>Add a game to begin your library.</p><button class="button subtle" data-action="import" data-focus="overview-import" ${busy ? 'disabled' : ''}>Add a game</button>`}</article><article class="dashboard-panel setup-overview"><h3>${icon('monitor')} Local setup</h3><div class="setup-summary"><span class="setup-icon">${icon('monitor')}</span><div><strong>Windows · mGBA</strong><span>${state.settings.emulatorPath ? 'Emulator configured' : 'Choose your emulator in Settings'}</span><small>Fullscreen ${state.settings.fullscreen ? 'on' : 'off'} · Return to launcher ${state.settings.returnToLauncher ? 'on' : 'off'}</small></div><button class="button subtle" data-action="settings" data-focus="overview-settings" aria-label="Configure launch preferences">Configure</button></div></article></section>`;
}
function hero(game) {
  const session = state.session?.gameId === game.id;
  return `<section class="hero art-${game.art || artForId(game.id)}" aria-labelledby="hero-title"><img class="hero-art" src="${artwork(game)}" alt=""><div class="hero-shade"></div><div class="hero-copy"><span class="hero-kicker"><i></i>${session ? 'YOUR GAME IS RUNNING' : game.lastPlayed ? 'CONTINUE YOUR JOURNEY' : 'READY WHEN YOU ARE'}</span><div class="hero-system">${esc(platformName(game.system))}${game.sample ? ' <span>· SAMPLE</span>' : ''}</div><h2 id="hero-title">${esc(game.title)}</h2><p>${session ? 'Enjoy the moment. Renew will be here when you return.' : 'Your next adventure starts here. Make it a good one.'}</p><div class="hero-actions"><button class="button play-button" data-action="play" data-id="${esc(game.id)}" data-focus="hero-play" ${busy || state.session ? 'disabled' : ''}>${icon('play')} ${session ? 'Playing' : 'Play game'} ${!session ? '<span class="key-hint">↵</span>' : ''}</button><button class="hero-favorite ${game.favorite ? 'is-favorite' : ''}" data-action="favorite" data-id="${esc(game.id)}" data-focus="hero-favorite" ${busy ? 'disabled' : ''} aria-label="${game.favorite ? 'Remove from' : 'Add to'} favorites" aria-pressed="${game.favorite}">${icon('heart')}</button></div><div class="hero-meta">${icon('clock')} ${esc(formatTime(game.playSeconds))}<span></span>${game.sample ? 'Original preview artwork' : 'Artwork by Renew'}</div></div><div class="art-caption"><span>YOUR SPACE TO PLAY</span><div>${icon('leaf')} RENEW ORIGINALS</div></div></section>`;
}
function emptyHero() { return `<section class="hero empty-hero"><img class="hero-art" src="./art/citadel-v1.png" alt=""><div class="hero-shade"></div><div class="hero-copy"><span class="hero-kicker"><i></i>A FRESH START</span><h2>A new home for<br>old favorites.</h2><p>Add the games you own. Pick your mGBA emulator.<br>Make a little time for yourself.</p><button class="button play-button" data-action="import" data-focus="empty-import" ${busy ? 'disabled' : ''}>${icon('plus')} Add your first game</button><div class="hero-meta">GBA, Game Boy Color & Game Boy</div></div><div class="art-caption"><span>EVERY ADVENTURE STARTS SOMEWHERE</span><div>${icon('leaf')} RENEW ORIGINALS</div></div></section>`; }
function card(game) { return `<article class="game-card ${selectedId === game.id ? 'selected-card' : ''}"><button class="game-art-button" data-action="select" data-id="${esc(game.id)}" data-focus="select-${esc(game.id)}" aria-label="Select ${esc(game.title)}" aria-pressed="${selectedId === game.id}"><img src="${artwork(game)}" alt="" loading="lazy"><span class="cover-system">${esc(game.system)}</span><span class="cover-wordmark">${esc(game.title)}</span><span class="cover-select">${icon(selectedId === game.id ? 'check' : 'chevron')}</span></button><div class="card-info"><div><button class="card-title" data-action="select" data-id="${esc(game.id)}" data-focus="title-${esc(game.id)}">${esc(game.title)}</button><p>${esc(formatTime(game.playSeconds))}${game.sample ? ' · Sample' : ''}</p></div><button class="card-menu" data-action="details" data-id="${esc(game.id)}" data-focus="details-${esc(game.id)}" aria-label="Details for ${esc(game.title)}">${icon('more')}</button></div>${game.favorite ? `<span class="card-favorite" aria-label="Favorite">${icon('heart')}</span>` : ''}</article>`; }
function emptyCollection() { return `<div class="empty-collection">${icon(ui.query ? 'search' : ui.view === 'favorites' ? 'heart' : 'game')}<h3>${ui.query ? 'No games found' : ui.view === 'favorites' ? 'Make room for your favorites' : ui.system !== 'all' ? 'No games for this system yet' : 'A good collection starts with one.'}</h3><p>${ui.query ? 'Try a different name or clear your filters.' : ui.view === 'favorites' ? 'Tap the heart on a game to keep it close.' : 'Add uncompressed .gba, .gbc or .gb files from your computer.'}</p>${ui.query || ui.system !== 'all' ? '<button class="button subtle" data-action="reset-filters">Clear filters</button>' : ui.view !== 'favorites' ? `<button class="button subtle" data-action="import" data-focus="empty-collection-import" ${busy ? 'disabled' : ''}>Add games</button>` : ''}</div>`; }
}
